# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ef72404958cf4ccfd408616ae4116f4298b1229e6ed4b28d6d7b9a482ece540dd36004dcf676bab68cb130aaa72cf21228b2a5a9b7345408462f23c5f8b7e65

test:
  secret_key_base: cede39642a14149cefcc404ddcfaddc4601a8dc2716baef2a8fbbf87b4d07965d59f0b1f5d66ba39863cb87154d29149285a1e9632be72afeba9b8b607dedc77

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
